namespace PLVirtualMachine.Common.VMDebug;

public enum EDebugFSMStatus {
	DEBUG_FSM_STATUS_PLAY,
	DEBUG_FSM_STATUS_WAIT,
	DEBUG_FSM_STATUS_STEPBYSTEP_STEP_INTO,
	DEBUG_FSM_STATUS_STEPBYSTEP_STEP_OVER,
	DEBUG_FSM_STATUS_STEPBYSTEP_CONTINUE
}