namespace Engine.Source.Services
{
  public enum CombatCryEnum
  {
    None,
    SeePlayerLowReputation,
    SeeEnemy,
    SeeWomanEnemy,
    FearEnemy,
    NeedHelp,
    FightWin,
    StopPursuit,
    Capitulation,
    Loot,
    SeeWeapon,
    RobberyReaction,
    SeeCrime,
    Catch,
    PunchUnblocked,
    Hurt,
    Blocked,
    HurtDodge,
    PunchBlocked,
    SuperPunch,
    Death,
    DeathInFire,
    DiseasedCough,
    DiseasedFever,
    DiseasedPainUp,
    DiseasedSleep,
    DiseasedDeath,
    CheerUp,
  }
}
