namespace PLVirtualMachine.Common.VMSpecialAttributes;

public enum ESpecialPropertyName {
	SPN_STORABLE_TITLE,
	SPN_STORABLE_DESCRIPTION,
	SPN_STORABLE_SPECIALDESCRIPTION,
	SPN_COMBINATION_DATA,
	SPN_STORABLE_TOOLTIP
}