namespace PLVirtualMachine.Dynamic
{
  public enum EEventUpdateMode
  {
    EVENT_UPDATE_MODE_ALWAYS,
    EVENT_UPDATE_MODE_PARAM_CHANGE,
    EVENT_UPDATE_MODE_OUTER_EVENT,
    EVENT_UPDATE_MODE_COMBINE,
    EVENT_UPDATE_MODE_NEVER,
  }
}
