namespace PLVirtualMachine.Common
{
  public enum EStateType
  {
    STATE_TYPE_STATE,
    STATE_TYPE_CASE_BRANCH,
    STATE_TYPE_FLIPFLOP_BRANCH,
    STATE_TYPE_MINVALUE_BRANCH,
    STATE_TYPE_MAXVALUE_BRANCH,
    STATE_TYPE_MESSAGE_CAST_BRANCH,
    STATE_TYPE_SPEECH,
    STATE_TYPE_GRAPH,
  }
}
