using System;
using System.Collections.Generic;
using System.Linq;

public class PhysicsSimulation : MonoBehaviour
{
  public int maxIterations = 1000;
  private SimulatedBody[] simulatedBodies;
  public Vector2 forceMinMax;
  public float forceAngleInDegrees;
  public bool randomizeForceAngle;
  private List<Rigidbody> generatedRigidbodies;
  private List<Collider> generatedColliders;

  [ContextMenu("Run Simulation")]
  public void RunSimulation()
  {
    AutoGenerateComponents();
    simulatedBodies = ((IEnumerable<Rigidbody>) UnityEngine.Object.FindObjectsOfType<Rigidbody>()).Select((Func<Rigidbody, SimulatedBody>) (rb => new SimulatedBody(rb, rb.transform.IsChildOf(this.transform)))).ToArray();
    foreach (SimulatedBody simulatedBody in simulatedBodies)
    {
      if (simulatedBody.isChild)
      {
        float num = UnityEngine.Random.Range(forceMinMax.x, forceMinMax.y);
        float f = (float) ((randomizeForceAngle ? (double) UnityEngine.Random.Range(0.0f, 360f) : forceAngleInDegrees) * (Math.PI / 180.0));
        Vector3 vector3 = new Vector3(Mathf.Sin(f), 0.0f, Mathf.Cos(f));
        simulatedBody.rigidbody.AddForce(vector3 * num, ForceMode.Impulse);
      }
    }
    Physics.autoSimulation = false;
    for (int index = 0; index < maxIterations; ++index)
    {
      Physics.Simulate(Time.fixedDeltaTime);
      if (simulatedBodies.All(body => body.rigidbody.IsSleeping() || !body.isChild))
        break;
    }
    Physics.autoSimulation = true;
    foreach (SimulatedBody simulatedBody in simulatedBodies)
    {
      if (!simulatedBody.isChild)
        simulatedBody.Reset();
    }
    RemoveAutoGeneratedComponents();
  }

  private void AutoGenerateComponents()
  {
    generatedRigidbodies = new List<Rigidbody>();
    generatedColliders = new List<Collider>();
    foreach (Transform transform in this.transform)
    {
      if (!(bool) (UnityEngine.Object) transform.GetComponent<Rigidbody>())
        generatedRigidbodies.Add(transform.gameObject.AddComponent<Rigidbody>());
      if (!(bool) (UnityEngine.Object) transform.GetComponent<Collider>())
        generatedColliders.Add((Collider) transform.gameObject.AddComponent<BoxCollider>());
    }
  }

  private void RemoveAutoGeneratedComponents()
  {
    foreach (UnityEngine.Object generatedRigidbody in generatedRigidbodies)
      UnityEngine.Object.DestroyImmediate(generatedRigidbody);
    foreach (UnityEngine.Object generatedCollider in generatedColliders)
      UnityEngine.Object.DestroyImmediate(generatedCollider);
  }

  [ContextMenu("Reset")]
  public void ResetAllBodies()
  {
    if (simulatedBodies == null)
      return;
    foreach (SimulatedBody simulatedBody in simulatedBodies)
      simulatedBody.Reset();
  }

  private struct SimulatedBody
  {
    public readonly Rigidbody rigidbody;
    public readonly bool isChild;
    private readonly Vector3 originalPosition;
    private readonly Quaternion originalRotation;
    private readonly Transform transform;

    public SimulatedBody(Rigidbody rigidbody, bool isChild)
    {
      this.rigidbody = rigidbody;
      this.isChild = isChild;
      transform = rigidbody.transform;
      originalPosition = rigidbody.position;
      originalRotation = rigidbody.rotation;
    }

    public void Reset()
    {
      transform.position = originalPosition;
      transform.rotation = originalRotation;
      if (!((UnityEngine.Object) rigidbody != (UnityEngine.Object) null))
        return;
      rigidbody.velocity = Vector3.zero;
      rigidbody.angularVelocity = Vector3.zero;
    }
  }
}
