public enum SuokCircleTutorialStateEnum
{
  Unknown,
  WaitForInitialDialogEnd,
  WaitForUnholster,
  WaitForPunch,
  WaitForUppercut,
  WaitForLowStamina,
  YourDamageIsLow,
  BlockExample,
  RuinBlockExample,
  StaminaGrowsFasterInBlock,
  WaitForFreeFight,
  FreeFight,
  YouWin,
  YouLoose,
  Ragdoll,
  AfterWinTalk,
}
